encoding: "UTF-8"
project:
  type: book # 必須存在，標記為書籍專案
  output-dir: _site/en
lang: en # 全域預設值，會被 profile 覆蓋

# CRITICAL: Define a dummy/placeholder book structure here
# This prevents the "Book contents must include a home page" error
book:
  # The 'chapters' key must be present, even if empty or placeholder
  chapters:
    - file: index.zh-hant.md