project:
  type: book
  output-dir: docs
encoding: "UTF-8"

book:
  title: "道／盜智框：AI 賽局手冊"
  author: "廖漢騰"
  date: "18/08/2025"
  chapters:
    - index.zh-hant.md
    - part: notes-action.zh-hant.md
      chapters:
      - notes-action_for_parents.zh-hant.md
      - notes-action_for_learners.zh-hant.md
    - notes-mind.zh-hant.md
    - toc.zh-hant.md
    - part: 01----problematics.zh-hant.md
      chapters:
        - 01-01-Turing_Test.zh-hant.md
        - 01-02-Chinese_Room.zh-hant.md
        - 01-03-Symbol_Grounding_Problem.zh-hant.md
        - 01-04-Frame_Problem.zh-hant.md
        - 01-05-Gestalt_Psychology.zh-hant.md
        - 01-06-Alignment_Control_Problem.zh-hant.md
        - 01-07-Language_Games.zh-hant.md
    - part: 02----schools_paradigms.zh-hant.md
      chapters:
        - 02-01-symbolic_ai.zh-hant.md
        - 02-02-statistical_ai.zh-hant.md
        - 02-03-neurosymbolic_ai.zh-hant.md
        - 02-04-agi.zh-hant.md
        - 02-05-connectionism.zh-hant.md
        - 02-06-behaviorism.zh-hant.md
        - 02-07-large_language_models.zh-hant.md
    - part: 03----symbolic_ai.zh-hant.md
      chapters:
        - 03-01-formal_logic.zh-hant.md
        - 03-02-automatic_dialogue_systems.zh-hant.md
        - 03-03-expert_systems.zh-hant.md
        - 03-04-knowledge_representation.zh-hant.md
        - 03-05-knowledge_graph.zh-hant.md
        - 03-06-semantic_web.zh-hant.md
        - 03-07-ontology.zh-hant.md
    - part: 04----statistical_ai.zh-hant.md
      chapters:
        - 04-01-probabilistic_association.zh-hant.md
        - 04-02-llm_chatbots.zh-hant.md
        - 04-03-neural_networks.zh-hant.md
        - 04-04-feature_engineering.zh-hant.md
        - 04-05-machine_learning_models.zh-hant.md
        - 04-06-llm_webassembly.zh-hant.md
        - 04-07-vector_space.zh-hant.md
    - part: 05----ai_orientations.zh-hant.md
      chapters:
        - 05-01-oriented_knowledge.zh-hant.md
        - 05-02-oriented_data.zh-hant.md
        - 05-03-oriented_agent.zh-hant.md
        - 05-04-oriented_task.zh-hant.md
        - 05-05-oriented_ethics.zh-hant.md
    - part: 06----analytics_decisions.zh-hant.md
      chapters:
        - 06-01-analysis_diagnostic.zh-hant.md
        - 06-02-analysis_predictive.zh-hant.md
        - 06-03-analysis_prescriptive.zh-hant.md
        - 06-04-analysis_descriptive.zh-hant.md
        - 06-05-analysis_generative.zh-hant.md
        - 06-06-decision_making_algorithm.zh-hant.md
    - part: 07----game_ai.zh-hant.md
      chapters:
        - 07-01-ieee_micromouse.zh-hant.md
        - 07-02-atari_dqn.zh-hant.md
        - 07-03-alphago.zh-hant.md
        - 07-04-poker_ai.zh-hant.md
        - 07-05-openai_five.zh-hant.md
        - 07-06-werewolf_ai.zh-hant.md
        - 07-07-battlefield_simulation.zh-hant.md
    - part: 08----embodied_ai.zh-hant.md
      chapters:
        - 08-01-robotics_and_physical_actuation.zh-hant.md
        - 08-02-perception_and_environment.zh-hant.md
        - 08-03-adaptive_robotics.zh-hant.md
        - 08-04-human_robot_interaction.zh-hant.md
        - 08-05-robot_safety_and_robustness.zh-hant.md
        - 08-06-robot_tasks_and_goals.zh-hant.md
    - part: 09----ai_math.zh-hant.md
      chapters:
        - 09-01-collaborative_filtering.zh-hant.md
        - 09-02-steepest_descent_method.zh-hant.md
        - 09-03-bayesian_network.zh-hant.md
        - 09-04-sparse_modeling.zh-hant.md
        - 09-05-markov_modeling.zh-hant.md
        - 09-06-monte_carlo_tree_search.zh-hant.md
        - 09-07-hebb_rule.zh-hant.md
        - 09-08-multi_agent_payoff_matrix.zh-hant.md
    - part: 10----ai_engineering.zh-hant.md
      chapters:
        - 10-01-API_MCP.zh-hant.md
        - 10-02-agent_reliability_evaluation.zh-hant.md
        - 10-03-prompt_engineering.zh-hant.md
        - 10-04-retrieval_augmented_generation.zh-hant.md
        - 10-05-context_engineering.zh-hant.md
        - 10-06-AI_PM.zh-hant.md
    - references.zh-hant.qmd
    - appendix_API.zh-hant.md
    - appendix_taxonomy.zh-hant.md
    - appendix_mindmap.zh-hant.md
  sidebar:
    style: "docked"
    #style: "floating"
    collapse-level: 1
    section-numbers: true
  page-footer:
    left: |
      ___ (2e) was written by ___.
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  cover-image: cover.png
  favicon: cover.png
  search: true
  repo-url: https://github.com/hanteng/frmAI/
  repo-actions: [edit]
  downloads: [pdf, epub]
  sharing: [twitter, facebook]

bibliography: references.bib

format:
  html:
    toc: true
    toc-depth: 5
    number-sections: true
    number-depth: 5
    clean-urls: false
    theme:
      - cosmo
      - brand
    cover-image: cover.png
    favicon: cover.jpg
#  pdf:
#    documentclass: scrreprt
#    cover-image: cover.svg
#  epub:
#    cover-image: cover.svg
