project:
  type: book

book:
  title: "Framing AI"
  author: "Han-Teng Liao"
  date: "18/08/2025"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd
  page-footer:
    left: |
      ___ (2e) was written by ___.
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  cover-image: cover.png
  favicon: cover.png

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand
    cover-image: cover.png
    favicon: cover.jpg
  pdf:
    documentclass: scrreprt
    cover-image: cover.svg
  epub:
    cover-image: cover.svg

