project:
  type: book
number-sections: true
number-depth: 3
toc-depth: 5
encoding: "UTF-8"

book:
  title: "道／盜智框"
  author: "廖漢騰"
  date: "18/08/2025"
  chapters:
    - index.zh-hant.qmd
    - part: 01----problematics.zh-hant.qmd
      chapters:
        - 01-01-Turing_Test.zh-hant.qmd
        - 01-02-Chinese_Room.zh-hant.qmd
        - 01-03-Symbol_Grounding_Problem.zh-hant.qmd
        - 01-04-Frame_Problem.zh-hant.qmd
        - 01-05-Gestalt_Psychology.zh-hant.qmd
        - 01-06-AI_Alignment_Control_Problem.zh-hant.qmd
        - 01-07-Language_Games.zh-hant.qmd
    - part: 05----ai_orientations.zh-hant.md
      chapters:
        - 05-01-oriented_knowledge.zh-hant.md
        - 05-02-oriented_data.zh-hant.md
        - 05-03-oriented_agent.zh-hant.md
        - 05-04-oriented_task.zh-hant.md
        - 05-05-oriented_ethics.zh-hant.md
    - references.zh-hant.qmd
  sidebar:
    style: "docked"
    #style: "floating"
    collapse-level: 4
    section-numbers: true
  page-footer:
    left: |
      ___ (2e) was written by ___.
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  cover-image: cover.png
  favicon: cover.png
  search: true
  repo-url: https://github.com/hanteng/frmAI/
  repo-actions: [edit]
  downloads: [pdf, epub]
  sharing: [twitter, facebook]

bibliography: references.bib

format:
  html:
    number-sections: true
    number-depth: 3
    toc-depth: 3
    theme:
      - cosmo
      - brand
    cover-image: cover.png
    favicon: cover.jpg
#  pdf:
#    documentclass: scrreprt
#    cover-image: cover.svg
#  epub:
#    cover-image: cover.svg

