project:
  type: book

book:
  title: "道／盜智框"
  author: "廖漢騰"
  date: "18/08/2025"
  chapters:
    - index.zh-hant.qmd
    - 1----problematics_zh-hant.qmd
    - summary.zh-hant.qmd
    - references.zh-hant.qmd
  page-footer:
    left: |
      ___ (2e) was written by ___.
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  cover-image: cover.png
  favicon: cover.png

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand
    cover-image: cover.png
    favicon: cover.jpg
  pdf:
    documentclass: scrreprt
    cover-image: cover.svg
  epub:
    cover-image: cover.svg

